server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: g1UcFTpoLlEfS9OwKJfj
            client-secret: RagdKt_wn1
            scope:
            - email
            - name
            - gender
            - birthday
            - birthyear
            - mobile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
          kakao:
            client-id: b950f80d8a295cb4e425e99fda77c90d
            redirect-uri: http://localhost:8000/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
            - profile_nickname
            - account_email
            - gender
            - birthday
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web1.cpvf6npjx9ou.ap-northeast-2.rds.amazonaws.com:3306/gjw_project?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin
    password: 1q2w3e4r
  
    
 
    
mybatis:
  mapper-locations:
  - /mappers/*.xml 
  

file:
  path: C:/kdh/kdh/git/giwproject/gjw.project/upload/
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

