server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
#  security:
#    user:
#      name: test
#      password: 1234

  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web1.cpvf6npjx9ou.ap-northeast-2.rds.amazonaws.com:3306/gjw_project?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin
    password: 1q2w3e4r
    
 
    
mybatis:
  mapper-locations:
  - /mappers/*.xml 
  

file:
  path: C:/kdh/kdh/git/giwproject/gjw.project/src/main/resources/static/img-kdh/
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

